backend:
  name: git-gateway
  branch: master
media_folder: src/public/images/uploads
public_folder: /images/uploads
site_url: https://aboutme-toshikisugiyama.netlify.app
logo_url: /images/profile.svg
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "string" }
      - { label: "Topics", name: "topics", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}
